apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  config.yaml: |
{{ .Values.config | toYaml | indent 4 }}