replicas: 1
imagePullPolicy: IfNotPresent
image:
  repository: ghcr.io/resmoio/kubernetes-event-exporter
  tag: "latest"

config:
    logLevel: error
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "dump"
    receivers:
      - name: "dump"
        stdout: {}

# annotations:
#   prometheus.io/scrape: 'true'
#   prometheus.io/port: '2112'
#   prometheus.io/path: '/metrics'


# resources:
#   requests:
#     memory: "64Mi"
#     cpu: "250m"
#   limits:
#     memory: "128Mi"
#     cpu: "500m"


# labels:
#   blabla: bla
